### ISSUE TITLE
code doesn't compile 

### ISSUE THREAD

**Issue by Ger123** [wal33d006/custom_contact_selection#1]
`SimplePermissions.requestPermission(Permission.ReadContacts);`

This line of code doesn't compile. Incompatible return types for `getContactsPermission()`

**Comment by wal33d006** [comment]
@Ger123 Please share the results of flutter doctor along with the whole error when the code is compiled. I cloned it, it's working fine at my end.

**Comment by wal33d006** [comment]
Closing it due to no response. If the code still doesn't compile, open another issue mentioning the output of flutter doctor and the compile time errors. Thanks.
